baseURL = 'JonaSabido.github.io/hugo'
languageCode = 'en-us'
title = 'First Hugo Site'
theme = 'terminal'

[menu]
  [[menu.main]]
	identifier = "about"
	name = "About"
	title = "About"
	url = "/about/"
	weight = 0
  [[menu.main]]
	identifier = "showcase"
	name = "Showcase"
	title = "Showcase"
	url = "/showcase/"
	weight = 0